version: '3.8'

services:
  dbreservasuh:
    image: mysql:latest
    container_name: DBReservasUH
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: roott
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: ReservasUH
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dbnet

volumes:
  mysql_data:

networks:
  dbnet:
    driver: bridge
